### ISSUE TITLE
Problem with update date/time

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#58]
Hello,
Let's say that I've just updated one of my plugins (Timezone to be precise):
![image](https://cloud.githubusercontent.com/assets/7569958/25739906/5a6c48e8-3184-11e7-9e3c-cbc4daa8ad29.png)

and then the catalog will reflect wrong UPDATED date/time:
![image](https://cloud.githubusercontent.com/assets/7569958/25739927/6e3491dc-3184-11e7-9856-d33d88eaac68.png)

Thank you,
Regards,
Tomolimo

**Comment by orthagh** [comment]
To follow this morning irc discussion, the issue is the ``date_updated`` field format is date not datetime.
We already have issues with this format (rss for example) but changin that field could break some things.
The next day following the update, normally the issue disappears.

I'll check what i can do for the day of update (tweaking display)
